import {z} from "zod";

const clean = z.string().trim().min(5);
const hex = z.string().regex(/^#[0-9A-Fa-f]{6}$/);
export const thumbnailContractSchema = z.object({
  version: z.literal("1.0"),
  exact_headline: z.string().trim().min(2).max(90),
  primary_subject: clean,
  secondary_subject: z.string().trim().min(5).nullable(),
  composition: z.string().trim().min(12),
  visual_tension: z.string().trim().min(12),
  forbidden_elements: z.array(z.string().trim().min(3)).min(2).max(20),
  palette: z.object({
    base: hex,
    accent: z.literal("#FFBD19"),
    text: z.literal("#F6F7F8"),
  }).strict(),
  format: z.object({width:z.literal(1280),height:z.literal(720)}).strict(),
  no_extra_text: z.literal(true),
}).strict().superRefine((value,ctx)=>{
  if(new Set(value.forbidden_elements.map(item=>item.toLocaleLowerCase("pt-BR"))).size!==value.forbidden_elements.length)ctx.addIssue({code:"custom",path:["forbidden_elements"],message:"Elementos proibidos não podem se repetir."});
});
export type ThumbnailContract = z.infer<typeof thumbnailContractSchema>;

/** This checks the editorial contract, not the pixels generated by a model. */
export function validateThumbnailContract(project:any,rawContract:unknown):string[] {
  const thumb=project.packaging?.thumbnails?.[0];
  if(!thumb)return ["Capa aprovada não encontrada em packaging.thumbnails[0]."];
  const parsed=thumbnailContractSchema.safeParse(rawContract);
  if(!parsed.success)return parsed.error.issues.map(issue=>`thumbnail.contract.${issue.path.join(".")}: ${issue.message}`);
  const contract=parsed.data;
  const errors:string[]=[];
  if(contract.exact_headline!==thumb.headline)errors.push("Headline do contrato diverge da headline aprovada no episódio.");
  if(!String(thumb.concept??"").trim())errors.push("Conceito editorial da capa está vazio.");
  return errors;
}
