"""Turn a fact-checked multi-story news edition into the existing ODE Live/Remotion contract.

This is not an LLM newsroom: inputs contain researched narration and independently
recorded sources. No sources, facts, or quotes are generated by this worker.
"""
from __future__ import annotations
import argparse
from datetime import date, datetime, timedelta
import json
import re
from pathlib import Path
from urllib.parse import urlparse


def require(condition: bool, message: str):
    if not condition:
        raise ValueError("news: " + message)


def validate(edition: dict, now: date | None = None) -> dict:
    now = now or date.today()
    require(edition.get("format") == "ode-news-roundup", "formato não reconhecido")
    episode = edition.get("edition_id", "")
    require(bool(re.fullmatch(r"noticias-\d{4}-\d{2}-\d{2}-(manha|tarde|noite)", episode)), "ID da edição inválido")
    day = date.fromisoformat(edition["edition_date"])
    require(episode == "noticias-" + day.isoformat() + "-" + edition.get("slot", ""), "ID e data não combinam")
    # Archived pilots are permitted but unattended publication of stale scripts is not.
    require(day <= now + timedelta(days=1), "não é permitido gerar notícia futura")
    require(edition.get("editorial_status") == "approved_for_private_pilot", "falta aprovação editorial do roteiro")
    require(isinstance(edition.get("reviewed_at"), str) and edition["reviewed_at"], "revisão não documentada")
    title = edition.get("title", "")
    require(isinstance(title, str) and 10 <= len(title) <= 100, "título fora do padrão")
    headline = edition.get("thumbnail_headline", "")
    require(isinstance(headline, str) and 6 <= len(headline) <= 36, "headline da capa inválida")
    stories = edition.get("stories", [])
    require(isinstance(stories, list) and 3 <= len(stories) <= 6, "uma edição exige 3 a 6 matérias")
    ids = [s.get("id") for s in stories]
    require(len(set(ids)) == len(ids), "pauta duplicada na mesma edição")
    for story in stories:
        require(isinstance(story.get("narration"), str) and len(story["narration"].split()) >= 90, "matéria curta demais")
        require(isinstance(story.get("headline"), str) and 6 <= len(story["headline"]) <= 65, "headline visual inválida")
        sources = story.get("sources", [])
        require(isinstance(sources, list) and len(sources) >= 2, "cada matéria exige ao menos 2 fontes")
        hosts = set()
        for source in sources:
            u = urlparse(source.get("url", ""))
            require(u.scheme == "https" and bool(u.hostname) and u.hostname != "localhost", "fonte sem URL HTTPS válida")
            hosts.add(u.hostname.lower().removeprefix("www."))
        require(len(hosts) >= 2, "fontes precisam ser de publicadores diferentes")
        require(len(story.get("checked_facts", [])) >= 2, "alegações precisam estar registradas na apuração")
        published = date.fromisoformat(story["published_at"])
        require(day - timedelta(days=3) <= published <= day, "notícia fora da janela de 72h")
        require(story.get("object_type") in ("package", "truck", "factory", "bank", "cash", "store", "data"), "objeto visual não aprovado")
    return edition


def anchors(narration: str) -> list[str]:
    tokens = list(re.finditer(r"\S+", narration))
    candidates = []
    for offset in range(0, len(tokens), 11):
        start = tokens[offset].start()
        end = tokens[min(offset + 4, len(tokens) - 1)].end()
        phrase = narration[start:end]
        if narration.count(phrase) == 1 and len(phrase) <= 140:
            candidates.append(phrase)
    require(len(candidates) >= 3, "não há âncoras únicas suficientes para sincronizar")
    return candidates


def stage(label: str, headline: str, metric: str, object_type: str) -> dict:
    return {
        "show_title": False, "camera_mode": "manual", "motion_profile": "narrative",
        "initial_camera": {"x": 50, "y": 50, "zoom": 1},
        "captions": {"enabled": True, "max_words": 6, "words_per_line": 3,
                     "max_lines": 2, "font_size": 64, "min_free_area_ratio": .30},
        "elements": [
            {"id": "section", "kind": "label", "label": label[:76],
             "x": 5, "y": 7, "width": 90, "height": 13, "label_size": 41, "surface": "none"},
            {"id": "headline", "kind": "label", "label": headline[:76],
             "x": 5, "y": 24, "width": 54, "height": 48, "label_size": 72,
             "surface": "none"},
            {"id": "subject", "kind": "object", "label": headline[:65],
             "object_type": object_type, "x": 60, "y": 22, "width": 37,
             "height": 59, "show_label": False, "surface": "none",
             "svg_motion": "assemble", "visual_role": "protagonist",
             "sustain": {"kind": "breathe", "amplitude": 14, "period_seconds": 7}},
            {"id": "metric", "kind": "label", "label": metric[:30],
             "x": 5, "y": 81, "width": 55, "height": 13, "label_size": 55,
             "surface": "none"},
        ],
        "connections": [],
    }


def scene(index: int, title: str, narration: str, label: str, headline: str, metric: str, object_type: str) -> dict:
    cues = anchors(narration)
    sequence = ["headline", "subject", "metric", "section"]
    beats = [{"anchor": anchor, "target_id": sequence[i % len(sequence)],
              "action": "focus", "treatment": "spotlight", "motion_seconds": .55,
              "behavior": "transform", "headline": headline}
             for i, anchor in enumerate(cues)]
    return {
        "id": f"scene-{index:02d}", "index": index, "title": title,
        "narration": narration, "claim_ids": [],
        "tts": {"delivery": "explain", "pause_ms": 120, "cues": []},
        "visual": {
            "type": "authored_stage", "transition": "cut",
            "stage": stage(label, headline, metric, object_type),
            "beats": beats,
        },
    }


def transform(data: dict) -> dict:
    data = validate(data)
    src = []
    for s in data["stories"]:
        for source in s["sources"]:
            src.append({
                "id": "S" + str(len(src) + 1),
                "title": s["slug"] + " | " + source["publisher"],
                "publisher": source["publisher"],
                "url": source["url"],
            })
    scenes = [scene(0, "Abertura do noticiário", data["intro"], "GIRO DO DINHEIRO",
                    "O QUE MUDOU HOJE?", "3 NOTÍCIAS", "data")]
    for i, item in enumerate(data["stories"], start=1):
        scenes.append(scene(i, item["slug"], item["narration"],
                            f"NOTÍCIA {i}  /  {item['label']}",
                            item["headline"], item["metric"], item["object_type"]))
    scenes.append(scene(len(scenes), "Encerramento", data["outro"],
                        "GIRO DO DINHEIRO", "ATÉ A PRÓXIMA EDIÇÃO",
                        "FATOS E CONTEXTO", "data"))
    contract = {
        "version": "1.0", "exact_headline": data["thumbnail_headline"],
        "primary_subject": data["thumbnail_primary"],
        "secondary_subject": None,
        "composition": "Composição editorial forte e exclusiva da manchete dominante, foco único e respiro para a headline.",
        "visual_tension": "A promessa de entrega mais rápida versus ausência de prazo garantido ao consumidor.",
        "forbidden_elements": ["prazo de entrega inventado", "documento falsificado", "selo oficial enganoso",
                               "gráfico sem dados reais", "texto extra", "marca d'água"],
        "palette": {"base": "#090B0D", "accent": "#FFBD19", "text": "#F6F7F8"},
        "format": {"width": 1280, "height": 720}, "no_extra_text": True,
    }
    description = (
        "Três notícias que ajudam a entender a economia e o cotidiano nesta edição do Giro do Dinheiro: "
        + "; ".join(s["slug"] for s in data["stories"])
        + ". Entenda o que foi confirmado, quais promessas ainda precisam se concretizar "
        + "e o que merece atenção."
    )
    return {
        "version": "1.0", "project_id": data["edition_id"], "title": data["title"],
        "presenter": {"gender": "male", "name": "Roberto"},
        "speech": {"pronunciations": {"AliExpress": "Áli Expréss", "Febraban": "Febraban"}, "ignore_pronunciation_terms": []},
        "story": {"subject": "Resumo de notícias de economia e negócios", "angle": "Fatos, consequência prática e incerteza",
                  "promise": "Notícias verificadas, sem promessas não comprovadas", "category": "finance"},
        "sources": src, "claims": [], "visual_assets": [],
        "visual_direction": {"concept": "Noticiário contextual e ágil", "world": "market", "secondary_color": "#FFBD19"},
        "editorial": {"format": "ode-news-roundup", "edition_date": data["edition_date"], "slot": data["slot"],
                      "editorial_status": data["editorial_status"], "source_balance": {"requires_diversity": True},
                      "youtube_suitability": {"risk_level": "low", "title_thumbnail_safe": True}},
        "packaging": {"titles": [{"id": "approved", "text": data["title"]}],
                      "thumbnails": [{"id": "approved", "headline": data["thumbnail_headline"],
                                      "contract": contract}]},
        "publication": {"description": description,
                        "seo": {"primary_keyword": "notícias economia hoje"},
                        "tags": ["giro do dinheiro", "notícias do dia", "economia", "Correios", "AliExpress",
                                 "petróleo", "ANP", "feriado bancário"],
                        "engagement_question": "Qual dessas notícias mais interessa ao seu bolso?",
                        "hashtags": ["#Noticias", "#Economia", "#ODinheiroExplica"]},
        "scenes": scenes,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()
    edition = json.loads(Path(args.input).read_text(encoding="utf-8"))
    project = transform(edition)
    target = Path(args.output)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(project, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"NEWS_EDITION_OK:{project['project_id']} stories={len(edition['stories'])} scenes={len(project['scenes'])}")


if __name__ == "__main__":
    main()
