"""Voice continuity v3.

Rules:
- Same model + same voice for the whole episode: copy source audio byte-for-byte.
- Mixed models: leave the reference-model scenes untouched and process only
  fallback scenes.
- A short vocal marker generated by the target model is prepended only at an
  actual model boundary.
"""

import argparse
import copy
import hashlib
import json
import math
from pathlib import Path
import re
import shutil
import subprocess

import numpy as np

VERSION = "adaptive-voice-continuity-v3"
PRIMARY_MODEL = "gemini-3.8-flash-tts"
SECONDARY_MODEL = "gemini-3.8-flash-lite-tts"
FALLBACK_MODEL = "gemini-3.1-flash-tts-preview"
SAMPLE_RATE = 48000
TRUE_PEAK_CEILING = -1.2
BANDS = [(80, 300), (300, 900), (900, 2500), (2500, 6000), (6000, 10000)]
MATCH_WINDOW_SECONDS = 5.0
MATCH_HOP_SECONDS = 2.5
SPECTRAL_MAX_GAIN_DB = 2.5
SPECTRAL_SHRINKAGE = 0.50
SPECTRAL_MAX_SLEW_DB = 0.65
MAX_STATIC_GAIN_DB = 3.0
STFT_SIZE = 4096
STFT_HOP = 2048


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(ffmpeg: str, args: list[str]):
    result = subprocess.run([ffmpeg, "-hide_banner", "-nostats", *args], capture_output=True)
    if result.returncode:
        raise RuntimeError(
            "ffmpeg failed: " + result.stderr.decode("utf-8", errors="replace")[-3000:]
        )
    return result


def duration_seconds(ffprobe: str, path: Path) -> float:
    result = subprocess.run(
        [
            ffprobe, "-v", "error", "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1", str(path),
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode:
        raise RuntimeError(f"ffprobe duration failed: {path}")
    duration = float(result.stdout.strip())
    if not math.isfinite(duration) or duration <= 0:
        raise RuntimeError(f"Invalid audio duration: {path}")
    return duration


def decode(ffmpeg: str, path: Path) -> np.ndarray:
    raw = run(
        ffmpeg,
        [
            "-v", "error", "-i", str(path), "-ac", "1", "-ar", str(SAMPLE_RATE),
            "-f", "f32le", "-",
        ],
    ).stdout
    samples = np.frombuffer(raw, dtype="<f4").copy()
    if len(samples) < SAMPLE_RATE or not np.isfinite(samples).all():
        raise RuntimeError(f"Invalid scene audio: {path}")
    return samples


def measure(ffmpeg: str, path: Path, target: float = -19.0) -> dict:
    result = run(
        ffmpeg,
        [
            "-i", str(path),
            "-af", f"loudnorm=I={target}:TP={TRUE_PEAK_CEILING}:LRA=11:print_format=json",
            "-f", "null", "-",
        ],
    )
    matches = re.findall(
        r'\{\s*"input_i".*?\}',
        result.stderr.decode("utf-8", errors="replace"),
        flags=re.S,
    )
    if not matches:
        raise RuntimeError(f"Loudness analysis did not return measurements: {path}")
    return json.loads(matches[-1])


def speech_profile(samples: np.ndarray, minimum_active_seconds: float = 5.0):
    frames = np.lib.stride_tricks.sliding_window_view(samples, STFT_SIZE)[::STFT_HOP]
    rms = np.sqrt(np.mean(frames.astype(np.float64) ** 2, axis=1))
    rms_db = 20 * np.log10(np.maximum(rms, 1e-12))
    gate_db = max(-45.0, float(np.percentile(rms_db, 75)) - 25.0)
    selected = frames[rms_db >= gate_db]
    active_seconds = len(selected) * STFT_HOP / SAMPLE_RATE
    details = {
        "active_seconds": round(active_seconds, 3),
        "activity_gate_dbfs": round(gate_db, 3),
    }
    if active_seconds < minimum_active_seconds or len(selected) < 16:
        return None, {**details, "reason": "insufficient-active-audio"}

    power = np.abs(np.fft.rfft(selected * np.hanning(STFT_SIZE), axis=1)) ** 2
    frequencies = np.fft.rfftfreq(STFT_SIZE, 1 / SAMPLE_RATE)
    band_power = np.stack([
        power[:, (frequencies >= lo) & (frequencies < hi)].sum(axis=1)
        for lo, hi in BANDS
    ], axis=1)
    normalized = band_power / np.maximum(band_power.sum(axis=1, keepdims=True), 1e-20)
    profile = np.median(10 * np.log10(np.maximum(normalized, 1e-12)), axis=0)
    return profile, {**details, "reason": "accepted"}


def residual_gain(reference_profile: np.ndarray, profile: np.ndarray) -> np.ndarray:
    residual = reference_profile - profile
    residual -= np.median(residual)
    return np.clip(
        residual * SPECTRAL_SHRINKAGE,
        -SPECTRAL_MAX_GAIN_DB,
        SPECTRAL_MAX_GAIN_DB,
    )


def build_adaptive_gain_windows(samples: np.ndarray, reference_profile: np.ndarray):
    duration = len(samples) / SAMPLE_RATE
    centers = np.unique(
        np.clip(
            np.arange(0.0, duration + MATCH_HOP_SECONDS, MATCH_HOP_SECONDS),
            0.0,
            duration,
        )
    )
    raw = []
    details = []
    half = MATCH_WINDOW_SECONDS / 2
    for center in centers:
        start = max(0.0, center - half)
        end = min(duration, center + half)
        if end - start < MATCH_WINDOW_SECONDS and duration > MATCH_WINDOW_SECONDS:
            if start <= 0:
                end = min(duration, MATCH_WINDOW_SECONDS)
            elif end >= duration:
                start = max(0.0, duration - MATCH_WINDOW_SECONDS)
        segment = samples[
            int(round(start * SAMPLE_RATE)):int(round(end * SAMPLE_RATE))
        ]
        profile, profile_details = speech_profile(segment, 1.25)
        raw.append(None if profile is None else residual_gain(reference_profile, profile))
        details.append({
            "center_seconds": round(float(center), 3),
            "profile": profile_details,
        })

    valid = [i for i, value in enumerate(raw) if value is not None]
    if not valid:
        return centers, np.zeros((len(centers), len(BANDS))), details

    filled = np.zeros((len(centers), len(BANDS)))
    for band in range(len(BANDS)):
        filled[:, band] = np.interp(
            np.arange(len(centers)),
            valid,
            [raw[i][band] for i in valid],
        )

    smoothed = filled.copy()
    if len(filled) > 2:
        smoothed[1:-1] = (
            0.25 * filled[:-2] + 0.50 * filled[1:-1] + 0.25 * filled[2:]
        )
    stable = smoothed.copy()
    for i in range(1, len(stable)):
        stable[i] = stable[i - 1] + np.clip(
            stable[i] - stable[i - 1],
            -SPECTRAL_MAX_SLEW_DB,
            SPECTRAL_MAX_SLEW_DB,
        )
    return centers, np.clip(stable, -SPECTRAL_MAX_GAIN_DB, SPECTRAL_MAX_GAIN_DB), details


def apply_spectral_match(
    samples: np.ndarray, centers: np.ndarray, gains: np.ndarray
) -> np.ndarray:
    if not np.any(np.abs(gains) > 1e-6):
        return samples.copy()

    pad = STFT_SIZE // 2
    padded = np.pad(samples.astype(np.float64), (pad, pad), mode="reflect")
    window = np.hanning(STFT_SIZE)
    frequencies = np.fft.rfftfreq(STFT_SIZE, 1 / SAMPLE_RATE)
    band_centers = np.array([math.sqrt(lo * hi) for lo, hi in BANDS])
    control_freqs = np.concatenate(([0.0], band_centers, [SAMPLE_RATE / 2]))
    output = np.zeros_like(padded)
    weight = np.zeros_like(padded)
    last_start = len(padded) - STFT_SIZE
    starts = list(range(0, max(1, last_start + 1), STFT_HOP))
    if starts[-1] != last_start:
        starts.append(last_start)

    for start in starts:
        frame = padded[start:start + STFT_SIZE]
        time_seconds = float(np.clip(
            (start + STFT_SIZE / 2 - pad) / SAMPLE_RATE,
            0.0,
            len(samples) / SAMPLE_RATE,
        ))
        temporal = np.array([
            np.interp(time_seconds, centers, gains[:, band])
            for band in range(len(BANDS))
        ])
        curve = np.interp(
            frequencies,
            control_freqs,
            np.concatenate(([0.0], temporal, [0.0])),
        )
        spectrum = np.fft.rfft(frame * window)
        spectrum *= np.power(10.0, curve / 20.0)
        reconstructed = np.fft.irfft(spectrum, n=STFT_SIZE)
        output[start:start + STFT_SIZE] += reconstructed * window
        weight[start:start + STFT_SIZE] += window ** 2

    valid = weight > 1e-10
    output[valid] /= weight[valid]
    return output[pad:pad + len(samples)].astype(np.float32)


def safe_source(directory: Path, filename: str) -> Path:
    resolved = (directory / filename).resolve()
    if not resolved.is_relative_to(directory.resolve()) or not resolved.is_file():
        raise RuntimeError(f"Missing scene audio or unsafe filename: {filename}")
    return resolved


def copy_passthrough(source: Path, output_dir: Path) -> Path:
    destination = output_dir / source.name
    shutil.copy2(source, destination)
    if file_sha256(source) != file_sha256(destination):
        raise RuntimeError(f"Passthrough copy changed audio: {source.name}")
    return destination


def write_float_wav(
    ffmpeg: str, samples: np.ndarray, raw_path: Path, wav_path: Path
) -> None:
    raw_path.write_bytes(samples.astype("<f4").tobytes())
    run(
        ffmpeg,
        [
            "-y", "-f", "f32le", "-ar", str(SAMPLE_RATE), "-ac", "1",
            "-i", str(raw_path), "-c:a", "pcm_f32le", str(wav_path),
        ],
    )


def prepend_marker(
    ffmpeg: str,
    marker: Path,
    narration: Path,
    pause_seconds: float,
    output: Path,
) -> None:
    filters = (
        f"[0:a]aresample={SAMPLE_RATE},aformat=channel_layouts=mono[m];"
        f"anullsrc=r={SAMPLE_RATE}:cl=mono:d={pause_seconds:.3f}[s];"
        f"[1:a]aresample={SAMPLE_RATE},aformat=channel_layouts=mono[n];"
        f"[m][s][n]concat=n=3:v=0:a=1[out]"
    )
    run(
        ffmpeg,
        [
            "-y", "-i", str(marker), "-i", str(narration),
            "-filter_complex", filters, "-map", "[out]",
            "-ar", str(SAMPLE_RATE), "-ac", "1",
            "-c:a", "pcm_s24le", str(output),
        ],
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-manifest", required=True)
    parser.add_argument("--source-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--output-manifest", required=True)
    args = parser.parse_args()

    source_dir = Path(args.source_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    input_manifest_path = Path(args.input_manifest).resolve()
    output_manifest_path = Path(args.output_manifest).resolve()
    ffmpeg = shutil.which("ffmpeg")
    ffprobe = shutil.which("ffprobe")
    if not ffmpeg or not ffprobe:
        raise RuntimeError("ffmpeg and ffprobe are required.")

    source_manifest = json.loads(input_manifest_path.read_text(encoding="utf-8"))
    scenes = source_manifest.get("scenes") or []
    if not scenes:
        raise RuntimeError("Source TTS manifest has no scenes.")

    output_dir.mkdir(parents=True, exist_ok=True)
    output_manifest_path.parent.mkdir(parents=True, exist_ok=True)

    models = [str(scene.get("model") or "") for scene in scenes]
    voices = {str(scene.get("voice") or "") for scene in scenes}
    homogeneous = len(set(models)) == 1 and len(voices) == 1
    result = copy.deepcopy(source_manifest)
    processed_scenes = []

    if homogeneous:
        for scene in scenes:
            source = safe_source(source_dir, scene["file"])
            destination = copy_passthrough(source, output_dir)
            processed = copy.deepcopy(scene)
            processed["file"] = destination.name
            processed["postprocess"] = {
                "version": VERSION,
                "mode": "passthrough-byte-identical",
                "reason": "single-model-single-voice-no-processing-needed",
                "source_sha256": file_sha256(source),
                "output_sha256": file_sha256(destination),
                "byte_identical": True,
                "eq_applied": False,
                "gain_applied": False,
                "limiter_applied": False,
                "resampled": False,
                "reencoded": False,
            }
            processed_scenes.append(processed)
            print(
                f"{scene['id']}: byte-identical passthrough; nenhum efeito aplicado.",
                flush=True,
            )

        result["scenes"] = processed_scenes
        result["postprocess"] = {
            "version": VERSION,
            "mode": "homogeneous-passthrough",
            "models_used": sorted(set(models)),
            "voice": next(iter(voices)),
            "effects_applied": False,
            "source_audio_preserved": True,
            "model_transition_count": 0,
        }
    else:
        reference_model = PRIMARY_MODEL if PRIMARY_MODEL in models else models[0]
        inspections = {}
        reference_profiles = []
        reference_loudness = []

        for scene in scenes:
            source = safe_source(source_dir, scene["file"])
            samples = decode(ffmpeg, source)
            loudness = measure(ffmpeg, source)
            profile, details = speech_profile(samples)
            inspections[scene["id"]] = {
                "path": source,
                "samples": samples,
                "loudness": loudness,
            }
            if scene.get("model") == reference_model:
                reference_loudness.append(float(loudness["input_i"]))
                if profile is not None:
                    reference_profiles.append(
                        (scene["id"], profile, details.get("active_seconds", 0.0))
                    )

        reference_profile = (
            np.median(np.stack([item[1] for item in reference_profiles]), axis=0)
            if reference_profiles and sum(item[2] for item in reference_profiles) >= 6.0
            else None
        )
        target_lufs = (
            float(np.median(reference_loudness))
            if reference_loudness else -19.0
        )

        for scene in scenes:
            scene_id = scene["id"]
            model = scene.get("model")
            info = inspections[scene_id]
            transition = scene.get("model_transition") or {}
            marker_shift = 0.0
            adaptive_windows = []

            if model == reference_model:
                base_output = copy_passthrough(info["path"], output_dir)
                reason = "reference-model-byte-identical"
                static_gain = 0.0
                eq_applied = False
                gain_applied = False
            else:
                matched = info["samples"].copy()
                gains = np.zeros((1, len(BANDS)))
                reason = "fallback-no-reference-profile"
                if reference_profile is not None:
                    centers, gains, adaptive_windows = build_adaptive_gain_windows(
                        info["samples"], reference_profile
                    )
                    matched = apply_spectral_match(
                        info["samples"], centers, gains
                    )
                    reason = f"slow-window-match-{model}-to-{reference_model}"

                raw_path = output_dir / f".{scene_id}.f32"
                premaster = output_dir / f".{scene_id}.premaster.wav"
                base_output = output_dir / f"{scene_id}.wav"
                try:
                    write_float_wav(ffmpeg, matched, raw_path, premaster)
                    pre = measure(ffmpeg, premaster, target_lufs)
                    static_gain = float(np.clip(
                        target_lufs - float(pre["input_i"]),
                        -MAX_STATIC_GAIN_DB,
                        MAX_STATIC_GAIN_DB,
                    ))
                    max_safe_gain = (
                        TRUE_PEAK_CEILING - float(pre["input_tp"])
                    )
                    static_gain = min(static_gain, max_safe_gain)
                    run(
                        ffmpeg,
                        [
                            "-y", "-i", str(premaster),
                            "-af", f"volume={static_gain:.5f}dB,aresample={SAMPLE_RATE}",
                            "-ar", str(SAMPLE_RATE), "-ac", "1",
                            "-c:a", "pcm_s24le", str(base_output),
                        ],
                    )
                finally:
                    raw_path.unlink(missing_ok=True)
                    premaster.unlink(missing_ok=True)

                eq_applied = bool(np.any(np.abs(gains) > 1e-6))
                gain_applied = abs(static_gain) > 1e-6

            final_output = base_output
            if transition.get("marker_status") in {"generated", "cached"}:
                marker = safe_source(
                    source_dir, str(transition.get("marker_file") or "")
                )
                marker_duration = float(
                    transition.get("marker_duration_seconds")
                    or duration_seconds(ffprobe, marker)
                )
                pause = float(transition.get("pause_after_seconds") or 0.0)
                marker_shift = marker_duration + pause
                combined = output_dir / f".{scene_id}.with-transition.wav"
                prepend_marker(
                    ffmpeg, marker, base_output, pause, combined
                )
                if base_output.suffix == ".wav":
                    base_output.unlink(missing_ok=True)
                final_output = output_dir / f"{scene_id}.wav"
                combined.replace(final_output)
                reason += "-with-model-switch-vocal-marker"

            processed = copy.deepcopy(scene)
            processed["file"] = final_output.name
            processed["duration_seconds"] = round(
                duration_seconds(ffprobe, final_output), 6
            )
            if marker_shift:
                for timing in processed.get("beat_timings", []):
                    if isinstance(
                        timing.get("audio_offset_seconds"), (int, float)
                    ):
                        timing["audio_offset_seconds"] = round(
                            timing["audio_offset_seconds"] + marker_shift, 6
                        )

            processed["postprocess"] = {
                "version": VERSION,
                "mode": "mixed-model-fallback-only",
                "reason": reason,
                "reference_model": reference_model,
                "adaptive_windows": adaptive_windows,
                "eq_applied": eq_applied,
                "gain_applied": gain_applied,
                "limiter_applied": False,
                "static_gain_db": round(float(static_gain), 4),
                "transition_marker_applied": bool(marker_shift),
                "transition_marker_shift_seconds": round(marker_shift, 4),
                "source_sha256": file_sha256(info["path"]),
                "output_sha256": file_sha256(final_output),
                "byte_identical": (
                    model == reference_model
                    and not marker_shift
                    and file_sha256(info["path"]) == file_sha256(final_output)
                ),
            }
            processed_scenes.append(processed)
            print(
                f"{scene_id}: model={model}; eq={eq_applied}; "
                f"gain={static_gain:+.2f}dB; marker={bool(marker_shift)}",
                flush=True,
            )

        result["scenes"] = processed_scenes
        result["total_duration_seconds"] = round(
            sum(float(scene["duration_seconds"]) for scene in processed_scenes),
            6,
        )
        result["postprocess"] = {
            "version": VERSION,
            "mode": "mixed-model-fallback-only",
            "models_used": sorted(set(models)),
            "voice": next(iter(voices)) if len(voices) == 1 else None,
            "reference_model": reference_model,
            "effects_applied": True,
            "primary_or_reference_audio_untouched": True,
            "fallback_only_spectral_match": True,
            "dynamic_loudness_normalization": False,
            "compressor": False,
            "limiter": False,
            "transition_marker_kind": "brief-throat-clear",
            "model_transition_count": int(
                source_manifest.get("model_transition_count", 0)
            ),
        }

    temporary = output_manifest_path.with_suffix(
        output_manifest_path.suffix + ".tmp"
    )
    temporary.write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary.replace(output_manifest_path)
    print(
        f"Voice continuity v3 complete: {result['postprocess']['mode']}",
        flush=True,
    )


if __name__ == "__main__":
    main()
